import { FolderWithCount, GuideWithFolder } from "@/types/db";

// Test Folders Data
export const TEST_FOLDERS: FolderWithCount[] = [
    {
        id: "fd_onboarding_001",
        userId: "user_001",
        name: "Onboarding",
        createdAt: "2024-10-01T08:00:00Z",
        guideCount: 5,
    },
    {
        id: "fd_demos_002",
        userId: "user_001",
        name: "Product Demos",
        createdAt: "2024-09-12T12:00:00Z",
        guideCount: 12,
    },
    {
        id: "fd_sops_003",
        userId: "user_001",
        name: "Internal SOPs",
        createdAt: "2024-07-18T15:45:00Z",
        guideCount: 8,
    },
    {
        id: "fd_marketing_004",
        userId: "user_001",
        name: "Marketing Assets",
        createdAt: "2024-08-05T11:25:00Z",
        guideCount: 3,
    },
];

// Test Guides Data
export const TEST_GUIDES: GuideWithFolder[] = [
    {
        id: "gd_searching_101",
        userId: "user_001",
        folderId: "fd_onboarding_001",
        folderName: "Onboarding",
        title: "Searching using Google",
        description: "Learn how to effectively search using Google",
        slug: "searching-using-google",
        status: "published",
        visibility: "public",
        createdAt: "2024-11-20T10:00:00Z",
        updatedAt: "2024-11-25T10:30:00Z",
    },
    {
        id: "gd_render_102",
        userId: "user_001",
        folderId: "fd_demos_002",
        folderName: "Product Demos",
        title: "Setting up Render account",
        description: "Step-by-step guide to create a Render account",
        slug: "setting-up-render-account",
        status: "draft",
        visibility: "private",
        createdAt: "2024-11-22T14:00:00Z",
        updatedAt: "2024-11-24T14:20:00Z",
    },
    {
        id: "gd_email_103",
        userId: "user_001",
        folderId: null,
        folderName: null,
        title: "How to send email",
        description: "Complete email sending tutorial",
        slug: "how-to-send-email",
        status: "published",
        visibility: "public",
        createdAt: "2024-11-21T09:00:00Z",
        updatedAt: "2024-11-23T09:15:00Z",
    },
    {
        id: "gd_sales_104",
        userId: "user_001",
        folderId: "fd_sops_003",
        folderName: "Internal SOPs",
        title: "Q4 Sales Report Export",
        description: "How to export quarterly sales reports",
        slug: "q4-sales-report-export",
        status: "published",
        visibility: "private",
        createdAt: "2024-11-25T08:00:00Z",
        updatedAt: "2024-11-26T08:45:00Z",
    },
    {
        id: "gd_sso_105",
        userId: "user_001",
        folderId: "fd_onboarding_001",
        folderName: "Onboarding",
        title: "Enable SSO for new hires",
        description: "Setting up single sign-on for employees",
        slug: "enable-sso-for-new-hires",
        status: "published",
        visibility: "private",
        createdAt: "2024-11-20T09:00:00Z",
        updatedAt: "2024-11-22T09:12:00Z",
    },
    {
        id: "gd_okrs_106",
        userId: "user_001",
        folderId: "fd_sops_003",
        folderName: "Internal SOPs",
        title: "Quarterly OKR Review",
        description: "Process for reviewing quarterly objectives",
        slug: "quarterly-okr-review",
        status: "published",
        visibility: "private",
        createdAt: "2024-11-15T07:00:00Z",
        updatedAt: "2024-11-18T07:00:00Z",
    },
    {
        id: "gd_linkedin_107",
        userId: "user_001",
        folderId: "fd_marketing_004",
        folderName: "Marketing Assets",
        title: "Schedule LinkedIn Post",
        description: "How to schedule posts on LinkedIn",
        slug: "schedule-linkedin-post",
        status: "published",
        visibility: "public",
        createdAt: "2024-11-18T16:00:00Z",
        updatedAt: "2024-11-20T16:05:00Z",
    },
];

// Recent guides (last 4 for dashboard)
export const TEST_RECENT_GUIDES = TEST_GUIDES.slice(0, 4);
