import { pgSchema, uuid, timestamp, text, boolean, jsonb, smallint } from "drizzle-orm/pg-core";

export const authSchema = pgSchema("auth");

export const authUsers = authSchema.table("users", {
    instanceId: uuid("instance_id"),
    id: uuid("id").primaryKey().notNull(),
    aud: text("aud"),
    role: text("role"),
    email: text("email"),
    encryptedPassword: text("encrypted_password"),
    emailConfirmedAt: timestamp("email_confirmed_at", { withTimezone: true, mode: 'string' }),
    invitedAt: timestamp("invited_at", { withTimezone: true, mode: 'string' }),
    confirmationToken: text("confirmation_token"),
    confirmationSentAt: timestamp("confirmation_sent_at", { withTimezone: true, mode: 'string' }),
    recoveryToken: text("recovery_token"),
    recoverySentAt: timestamp("recovery_sent_at", { withTimezone: true, mode: 'string' }),
    emailChangeTokenNew: text("email_change_token_new"),
    emailChange: text("email_change"),
    emailChangeSentAt: timestamp("email_change_sent_at", { withTimezone: true, mode: 'string' }),
    lastSignInAt: timestamp("last_sign_in_at", { withTimezone: true, mode: 'string' }),
    rawAppMetaData: jsonb("raw_app_meta_data"),
    rawUserMetaData: jsonb("raw_user_meta_data"),
    isSuperAdmin: boolean("is_super_admin"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
    phone: text("phone"),
    phoneConfirmedAt: timestamp("phone_confirmed_at", { withTimezone: true, mode: 'string' }),
    phoneChange: text("phone_change").default(''),
    phoneChangeToken: text("phone_change_token").default(''),
    phoneChangeSentAt: timestamp("phone_change_sent_at", { withTimezone: true, mode: 'string' }),
    emailChangeTokenCurrent: text("email_change_token_current").default(''),
    emailChangeConfirmStatus: smallint("email_change_confirm_status").default(0),
    bannedUntil: timestamp("banned_until", { withTimezone: true, mode: 'string' }),
    reauthenticationToken: text("reauthentication_token").default(''),
    reauthenticationSentAt: timestamp("reauthentication_sent_at", { withTimezone: true, mode: 'string' }),
    isSsoUser: boolean("is_sso_user").default(false).notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
    isAnonymous: boolean("is_anonymous").default(false).notNull(),
});
