/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebinarRouteImport } from './routes/webinar'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedGuideIdRouteImport } from './routes/shared/$guideId'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppUpgradeRouteImport } from './routes/app/upgrade'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedSteppsRouteImport } from './routes/app/_authed/stepps'
import { Route as AppAuthedSettingsRouteImport } from './routes/app/_authed/settings'
import { Route as AppAuthedSteppsIndexRouteImport } from './routes/app/_authed/stepps/index'
import { Route as AppAuthedEditorIndexRouteImport } from './routes/app/_authed/editor/index'
import { Route as AppAuthedCarouselIndexRouteImport } from './routes/app/_authed/carousel/index'
import { Route as AppAuthedSteppsGuideIdRouteImport } from './routes/app/_authed/stepps/$guideId'
import { Route as AppAuthedFolderFolderIdRouteImport } from './routes/app/_authed/folder/$folderId'
import { Route as AppAuthedEditorGuideIdRouteImport } from './routes/app/_authed/editor/$guideId'
import { Route as AppAuthedCarouselEditorRouteImport } from './routes/app/_authed/carousel/editor'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WebinarRoute = WebinarRouteImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedGuideIdRoute = SharedGuideIdRouteImport.update({
  id: '/shared/$guideId',
  path: '/shared/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSteppsRoute = AppAuthedSteppsRouteImport.update({
  id: '/stepps',
  path: '/stepps',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSettingsRoute = AppAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSteppsIndexRoute = AppAuthedSteppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedSteppsRoute,
} as any)
const AppAuthedEditorIndexRoute = AppAuthedEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedCarouselIndexRoute = AppAuthedCarouselIndexRouteImport.update({
  id: '/carousel/',
  path: '/carousel/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSteppsGuideIdRoute = AppAuthedSteppsGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => AppAuthedSteppsRoute,
} as any)
const AppAuthedFolderFolderIdRoute = AppAuthedFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedEditorGuideIdRoute = AppAuthedEditorGuideIdRouteImport.update({
  id: '/editor/$guideId',
  path: '/editor/$guideId',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedCarouselEditorRoute = AppAuthedCarouselEditorRouteImport.update({
  id: '/carousel/editor',
  path: '/carousel/editor',
  getParentRoute: () => AppAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guides': typeof GuidesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/webinar': typeof WebinarRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/upgrade': typeof AppUpgradeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shared/$guideId': typeof SharedGuideIdRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app/stepps': typeof AppAuthedSteppsRouteWithChildren
  '/app/': typeof AppAuthedIndexRoute
  '/app/carousel/editor': typeof AppAuthedCarouselEditorRoute
  '/app/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/folder/$folderId': typeof AppAuthedFolderFolderIdRoute
  '/app/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
  '/app/carousel': typeof AppAuthedCarouselIndexRoute
  '/app/editor': typeof AppAuthedEditorIndexRoute
  '/app/stepps/': typeof AppAuthedSteppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guides': typeof GuidesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/webinar': typeof WebinarRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shared/$guideId': typeof SharedGuideIdRoute
  '/app/settings': typeof AppAuthedSettingsRoute
  '/app/carousel/editor': typeof AppAuthedCarouselEditorRoute
  '/app/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/folder/$folderId': typeof AppAuthedFolderFolderIdRoute
  '/app/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
  '/app/carousel': typeof AppAuthedCarouselIndexRoute
  '/app/editor': typeof AppAuthedEditorIndexRoute
  '/app/stepps': typeof AppAuthedSteppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guides': typeof GuidesRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/webinar': typeof WebinarRoute
  '/app': typeof AppRouteWithChildren
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/upgrade': typeof AppUpgradeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/shared/$guideId': typeof SharedGuideIdRoute
  '/app/_authed/settings': typeof AppAuthedSettingsRoute
  '/app/_authed/stepps': typeof AppAuthedSteppsRouteWithChildren
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/carousel/editor': typeof AppAuthedCarouselEditorRoute
  '/app/_authed/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/_authed/folder/$folderId': typeof AppAuthedFolderFolderIdRoute
  '/app/_authed/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
  '/app/_authed/carousel/': typeof AppAuthedCarouselIndexRoute
  '/app/_authed/editor/': typeof AppAuthedEditorIndexRoute
  '/app/_authed/stepps/': typeof AppAuthedSteppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/guides'
    | '/payments'
    | '/privacy'
    | '/terms'
    | '/webinar'
    | '/app'
    | '/app/upgrade'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/payment/cancel'
    | '/payment/success'
    | '/shared/$guideId'
    | '/app/settings'
    | '/app/stepps'
    | '/app/'
    | '/app/carousel/editor'
    | '/app/editor/$guideId'
    | '/app/folder/$folderId'
    | '/app/stepps/$guideId'
    | '/app/carousel'
    | '/app/editor'
    | '/app/stepps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/guides'
    | '/payments'
    | '/privacy'
    | '/terms'
    | '/webinar'
    | '/app'
    | '/app/upgrade'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/payment/cancel'
    | '/payment/success'
    | '/shared/$guideId'
    | '/app/settings'
    | '/app/carousel/editor'
    | '/app/editor/$guideId'
    | '/app/folder/$folderId'
    | '/app/stepps/$guideId'
    | '/app/carousel'
    | '/app/editor'
    | '/app/stepps'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/guides'
    | '/payments'
    | '/privacy'
    | '/terms'
    | '/webinar'
    | '/app'
    | '/app/_authed'
    | '/app/upgrade'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/payment/cancel'
    | '/payment/success'
    | '/shared/$guideId'
    | '/app/_authed/settings'
    | '/app/_authed/stepps'
    | '/app/_authed/'
    | '/app/_authed/carousel/editor'
    | '/app/_authed/editor/$guideId'
    | '/app/_authed/folder/$folderId'
    | '/app/_authed/stepps/$guideId'
    | '/app/_authed/carousel/'
    | '/app/_authed/editor/'
    | '/app/_authed/stepps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GuidesRoute: typeof GuidesRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WebinarRoute: typeof WebinarRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  SharedGuideIdRoute: typeof SharedGuideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinar': {
      id: '/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof WebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$guideId': {
      id: '/shared/$guideId'
      path: '/shared/$guideId'
      fullPath: '/shared/$guideId'
      preLoaderRoute: typeof SharedGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/stepps': {
      id: '/app/_authed/stepps'
      path: '/stepps'
      fullPath: '/app/stepps'
      preLoaderRoute: typeof AppAuthedSteppsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/settings': {
      id: '/app/_authed/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthedSettingsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/stepps/': {
      id: '/app/_authed/stepps/'
      path: '/'
      fullPath: '/app/stepps/'
      preLoaderRoute: typeof AppAuthedSteppsIndexRouteImport
      parentRoute: typeof AppAuthedSteppsRoute
    }
    '/app/_authed/editor/': {
      id: '/app/_authed/editor/'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppAuthedEditorIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/carousel/': {
      id: '/app/_authed/carousel/'
      path: '/carousel'
      fullPath: '/app/carousel'
      preLoaderRoute: typeof AppAuthedCarouselIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/stepps/$guideId': {
      id: '/app/_authed/stepps/$guideId'
      path: '/$guideId'
      fullPath: '/app/stepps/$guideId'
      preLoaderRoute: typeof AppAuthedSteppsGuideIdRouteImport
      parentRoute: typeof AppAuthedSteppsRoute
    }
    '/app/_authed/folder/$folderId': {
      id: '/app/_authed/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/app/folder/$folderId'
      preLoaderRoute: typeof AppAuthedFolderFolderIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/editor/$guideId': {
      id: '/app/_authed/editor/$guideId'
      path: '/editor/$guideId'
      fullPath: '/app/editor/$guideId'
      preLoaderRoute: typeof AppAuthedEditorGuideIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/carousel/editor': {
      id: '/app/_authed/carousel/editor'
      path: '/carousel/editor'
      fullPath: '/app/carousel/editor'
      preLoaderRoute: typeof AppAuthedCarouselEditorRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedSteppsRouteChildren {
  AppAuthedSteppsGuideIdRoute: typeof AppAuthedSteppsGuideIdRoute
  AppAuthedSteppsIndexRoute: typeof AppAuthedSteppsIndexRoute
}

const AppAuthedSteppsRouteChildren: AppAuthedSteppsRouteChildren = {
  AppAuthedSteppsGuideIdRoute: AppAuthedSteppsGuideIdRoute,
  AppAuthedSteppsIndexRoute: AppAuthedSteppsIndexRoute,
}

const AppAuthedSteppsRouteWithChildren = AppAuthedSteppsRoute._addFileChildren(
  AppAuthedSteppsRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedSettingsRoute: typeof AppAuthedSettingsRoute
  AppAuthedSteppsRoute: typeof AppAuthedSteppsRouteWithChildren
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedCarouselEditorRoute: typeof AppAuthedCarouselEditorRoute
  AppAuthedEditorGuideIdRoute: typeof AppAuthedEditorGuideIdRoute
  AppAuthedFolderFolderIdRoute: typeof AppAuthedFolderFolderIdRoute
  AppAuthedCarouselIndexRoute: typeof AppAuthedCarouselIndexRoute
  AppAuthedEditorIndexRoute: typeof AppAuthedEditorIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedSettingsRoute: AppAuthedSettingsRoute,
  AppAuthedSteppsRoute: AppAuthedSteppsRouteWithChildren,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedCarouselEditorRoute: AppAuthedCarouselEditorRoute,
  AppAuthedEditorGuideIdRoute: AppAuthedEditorGuideIdRoute,
  AppAuthedFolderFolderIdRoute: AppAuthedFolderFolderIdRoute,
  AppAuthedCarouselIndexRoute: AppAuthedCarouselIndexRoute,
  AppAuthedEditorIndexRoute: AppAuthedEditorIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GuidesRoute: GuidesRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WebinarRoute: WebinarRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  SharedGuideIdRoute: SharedGuideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
