/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedSteppsRouteImport } from './routes/app/_authed/stepps'
import { Route as AppAuthedSteppsGuideIdRouteImport } from './routes/app/_authed/stepps/$guideId'
import { Route as AppAuthedEditorGuideIdRouteImport } from './routes/app/_authed/editor/$guideId'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSteppsRoute = AppAuthedSteppsRouteImport.update({
  id: '/stepps',
  path: '/stepps',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSteppsGuideIdRoute = AppAuthedSteppsGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => AppAuthedSteppsRoute,
} as any)
const AppAuthedEditorGuideIdRoute = AppAuthedEditorGuideIdRouteImport.update({
  id: '/editor/$guideId',
  path: '/editor/$guideId',
  getParentRoute: () => AppAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedRouteWithChildren
  '/app/stepps': typeof AppAuthedSteppsRouteWithChildren
  '/app/': typeof AppAuthedIndexRoute
  '/app/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedIndexRoute
  '/app/stepps': typeof AppAuthedSteppsRouteWithChildren
  '/app/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/_authed/stepps': typeof AppAuthedSteppsRouteWithChildren
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/editor/$guideId': typeof AppAuthedEditorGuideIdRoute
  '/app/_authed/stepps/$guideId': typeof AppAuthedSteppsGuideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/stepps'
    | '/app/'
    | '/app/editor/$guideId'
    | '/app/stepps/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/stepps'
    | '/app/editor/$guideId'
    | '/app/stepps/$guideId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_authed'
    | '/app/_authed/stepps'
    | '/app/_authed/'
    | '/app/_authed/editor/$guideId'
    | '/app/_authed/stepps/$guideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/stepps': {
      id: '/app/_authed/stepps'
      path: '/stepps'
      fullPath: '/app/stepps'
      preLoaderRoute: typeof AppAuthedSteppsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/stepps/$guideId': {
      id: '/app/_authed/stepps/$guideId'
      path: '/$guideId'
      fullPath: '/app/stepps/$guideId'
      preLoaderRoute: typeof AppAuthedSteppsGuideIdRouteImport
      parentRoute: typeof AppAuthedSteppsRoute
    }
    '/app/_authed/editor/$guideId': {
      id: '/app/_authed/editor/$guideId'
      path: '/editor/$guideId'
      fullPath: '/app/editor/$guideId'
      preLoaderRoute: typeof AppAuthedEditorGuideIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedSteppsRouteChildren {
  AppAuthedSteppsGuideIdRoute: typeof AppAuthedSteppsGuideIdRoute
}

const AppAuthedSteppsRouteChildren: AppAuthedSteppsRouteChildren = {
  AppAuthedSteppsGuideIdRoute: AppAuthedSteppsGuideIdRoute,
}

const AppAuthedSteppsRouteWithChildren = AppAuthedSteppsRoute._addFileChildren(
  AppAuthedSteppsRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedSteppsRoute: typeof AppAuthedSteppsRouteWithChildren
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedEditorGuideIdRoute: typeof AppAuthedEditorGuideIdRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedSteppsRoute: AppAuthedSteppsRouteWithChildren,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedEditorGuideIdRoute: AppAuthedEditorGuideIdRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
