import { z } from "zod";
import { router, publicProcedure } from "../trpc-instance";
import { TRPCError } from "@trpc/server";
import { getUserGuides } from "@repo/data-ops/queries";

export const guideExportsRouter = router({
    getAll: publicProcedure.query(async () => {
        // TODO: Get userId from context (auth)
        const userId = "f1d84914-ec7c-4b1a-9a89-eaeff6b2f366"; // Hardcoded for now
        const guides = await getUserGuides(userId);

        // Transform guides with exported_docs into flat list of exports
        const exports = guides.flatMap(guide => {
            if (!guide.exportedDocs) return [];

            const exportedDocs = guide.exportedDocs as Record<string, {
                status: string;
                url?: string;
                last_updated?: string;
            }>;

            return Object.entries(exportedDocs).map(([type, doc]) => ({
                id: `${guide.id}-${type}`,
                guideId: guide.id,
                guideTitle: guide.title || "Untitled Guide",
                type: type as "pdf" | "html" | "markdown",
                fileUrl: doc.url || null,
                status: doc.status?.toLowerCase() || "pending",
                createdAt: doc.last_updated || guide.createdAt,
            }));
        });

        // Sort by createdAt descending
        exports.sort((a, b) => {
            const dateA = new Date(a.createdAt || 0).getTime();
            const dateB = new Date(b.createdAt || 0).getTime();
            return dateB - dateA;
        });

        return exports;
    }),

    triggerExport: publicProcedure
        .input(z.object({
            guideId: z.string(),
            format: z.enum(["pdf", "html", "word"]),
            htmlContent: z.string(), // HTML content generated by frontend
        }))
        .mutation(async ({ input, ctx }) => {
            const { guideId, format, htmlContent } = input;

            // Only PDF and HTML are supported for now
            if (format === 'word') {
                throw new TRPCError({
                    code: 'BAD_REQUEST',
                    message: 'Word export is not yet supported',
                });
            }

            // Get accountId from context (assuming auth is set up and user has an account)
            // For now, we might need to fetch it or use a placeholder if not in context.
            // Based on guides.ts, userId is hardcoded, so we might need to do the same or fetch the guide to get userId.

            // Fetch guide to verify ownership and get userId (which acts as accountId for now)
            // We can't easily import getGuide here if it's not available in the worker context directly without DB access.
            // For now, use the hardcoded userId from guides.ts as a fallback
            // TODO: Replace with actual auth context (ctx.user.id)
            const accountId = "f1d84914-ec7c-4b1a-9a89-eaeff6b2f366"; //delete we have the accountId in the data-service

            try {
                // Call data-service Hono route
                const response = await ctx.env.BACKEND_SERVICE.fetch(
                    new Request('https://internal/exports/trigger', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            guideId,
                            accountId, //doesn't need to exist
                            format,
                            htmlContent,
                        }),
                    })
                );

                if (!response.ok) {
                    const error = await response.json() as { error?: string };
                    throw new Error(error.error || 'Failed to trigger export');
                }

                const result = await response.json() as { success: boolean; status: string };
                return result;
            } catch (error) {
                console.error("Failed to trigger export workflow:", error);
                throw new TRPCError({
                    code: 'INTERNAL_SERVER_ERROR',
                    message: 'Failed to start export process',
                });
            }
        }),
});
